version: '3'

services:

  savannah_backend:
    container_name: savannah_backend
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/apps/savannah/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=savannah
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=savannah
